version: '3.3'
services:
  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'   
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'      
      MYSQL_ROOT_PASSWORD: 'password'
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'  
    networks:
      - local-loqin

  login:
    image: ggabriell4555/loginapp:1.3
    container_name: login-app
    restart: always
    environment:
      MYSQL_HOST: database 
      MYSQL_USER: 'root'
      MYSQL_PASS: 'password'
      SERVER_PORT: '8082'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n"
    links:
       - database
    ports:
      - '8080:8082'
      - '5005:5005'
    expose:
      - '8082'
      - '5005'
    networks:
      - local-loqin
    depends_on:
      database:
        condition: service_healthy
        restart: true

networks:
  local-loqin:
    driver: bridge
